name: Tests (Client Lib)

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client

    steps:
      - uses: actions/checkout@v2
      - run: yarn install
        working-directory: ${{env.working-directory}}
      - run: yarn test
        working-directory: ${{env.working-directory}}
